### ISSUE TITLE
Latest version 6.1.0 lacks flavor for `Cata`

### ISSUE THREAD

**Issue by doneykoo** [mitchnull/RangeDisplay#5]
- see files list on curseforge [RangeDisplay - Files - World of Warcraft Addons - CurseForge](https://www.curseforge.com/wow/addons/range-display/files/all?page=1&pageSize=20)
- see v6.1.0, no Cata flavor [RangeDisplay - Files v6.1.0 - World of Warcraft Addons - CurseForge](https://www.curseforge.com/wow/addons/range-display/files/5367449)
- while v6.0.7, with Cata flavor [RangeDisplay - Files v6.0.7 - World of Warcraft Addons - CurseForge](https://www.curseforge.com/wow/addons/range-display/files/5327952)

**Comment by mitchnull** [comment]
Pushed a new tag, and now the Cata version was generated as well as far as I can see.  The package must have had a bad day the last time around.  Then it messed up the externals in v6.1.1... Please check v6.1.2
